---
version: '2.1'
services:
  demo:
    build:
      context: .
    working_dir: /usr/src/app
    environment:
      - REDIS_ENDPOINT=http://demo-redis:6379
    ports:
      - "8080:8080"
    volumes:
      - ~/.m2:/root/.m2
      - .:/usr/src/app
    depends_on:
      - demo-redis
  demo-redis:
    image: redis:alpine
    ports:
      - "6379:6379"
 
